### membuat user
POST http://localhost:5000/users
Content-Type: application/json

{
    "nama": "Badrul Akhyar",
    "email": "badrul@gmail.com",
    "password": "qwertyuiop",
    "confPassword": "qwertyuiop",
    "role": "admin"
}

### melihat semua user
GET http://localhost:5000/users

#### melihat user yang dipilih
GET http://localhost:5000/users/251234c5-6be7-4e48-b486-bce2beccf059

### mengupdate user
PATCH http://localhost:5000/users/251234c5-6be7-4e48-b486-bce2beccf059
Content-Type: application/json

{
    "nama": "Badrul Akhyar",
    "email": "badrul@gmail.com",
    "password": "qwertyuiop",
    "confPassword": "qwertyuiop",
    "role": "admin"
}

### menghapus user
DELETE http://localhost:5000/users/fc95474a-ad9c-41d8-861a-2709eded1618


##################################################################################################
### login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "badrul@gmail.com",
    "password": "qwertyuiop"
}

### user yg sedang login
GET http://localhost:5000/me

### logout
DELETE http://localhost:5000/logout


##########################################################################################
### membuat pemesanan
POST http://localhost:5000/pemesanan
Content-Type: application/json

{
    "nama": "NPK",
    "harga": "19000"
}

### melihat semua pemesanan
GET http://localhost:5000/pemesanan

### melihat pesanan berdasarkn id
GET http://localhost:5000/pemesanan/38eec6ee-eb40-484f-a17c-880634c144dd

### mengupdate pesanan
PATCH  http://localhost:5000/pemesanan/38eec6ee-eb40-484f-a17c-880634c144dd
Content-Type: application/json

{
    "nama": "NPK",
    "harga": "29000"
}

### mengapus pemesanan
DELETE http://localhost:5000/pemesanan/38eec6ee-eb40-484f-a17c-880634c144dd


###################################################################################################
### membuat pendaftaran
POST http://localhost:5000/daftar
Content-Type: application/json

{
    "nama": "pes",
    "alamat": "jakarta",
    "NIK": "1355475689908325",
    "NO_KK": "1763984978556",
    "luasLahan":"3500 hektar"
}

###melihat semua data daftar
GET http://localhost:5000/daftar

### melihat pendaftaran berdasarkan uuid
GET http://localhost:5000/daftar/2d9b1ed4-8efb-49c2-b073-54804306b607

### mengupdate pendaftaran
PATCH http://localhost:5000/daftar/2d9b1ed4-8efb-49c2-b073-54804306b607
Content-Type: application/json

{
    "nama": "bedul",
    "alamat": "jakarta",
    "NIK": "1355475689908325",
    "NO_KK": "1763984978556",
    "luasLahan":"3500 hektar"
}

### menhapus pendaftaran
DELETE http://localhost:5000/daftar/2d9b1ed4-8efb-49c2-b073-54804306b607